// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfb3NchrAkbFVX8vyV176vLTOToYd8qc',
    appId: '1:937337910956:web:4efe5076bcb0fd78151109',
    messagingSenderId: '937337910956',
    projectId: 'microhelp-hnm',
    authDomain: 'microhelp-hnm.firebaseapp.com',
    storageBucket: 'microhelp-hnm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcGe6bwYjzLKsFdPRPNFHpKfOJ5eFFwU',
    appId: '1:937337910956:android:0ed3d13eb80aaea2151109',
    messagingSenderId: '937337910956',
    projectId: 'microhelp-hnm',
    storageBucket: 'microhelp-hnm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9AVV8E-BYlf0xQRi4u_GIAiv4y77Edg',
    appId: '1:937337910956:ios:ea94b13631e7e37a151109',
    messagingSenderId: '937337910956',
    projectId: 'microhelp-hnm',
    storageBucket: 'microhelp-hnm.firebasestorage.app',
    iosClientId: '937337910956-crsaakknmpf9dappi8ev893b0c9jbrp4.apps.googleusercontent.com',
    iosBundleId: 'com.microhelp.microHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9AVV8E-BYlf0xQRi4u_GIAiv4y77Edg',
    appId: '1:937337910956:ios:ea94b13631e7e37a151109',
    messagingSenderId: '937337910956',
    projectId: 'microhelp-hnm',
    storageBucket: 'microhelp-hnm.firebasestorage.app',
    iosClientId: '937337910956-crsaakknmpf9dappi8ev893b0c9jbrp4.apps.googleusercontent.com',
    iosBundleId: 'com.microhelp.microHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARfb3NchrAkbFVX8vyV176vLTOToYd8qc',
    appId: '1:937337910956:web:6840b9e90d9cd641151109',
    messagingSenderId: '937337910956',
    projectId: 'microhelp-hnm',
    authDomain: 'microhelp-hnm.firebaseapp.com',
    storageBucket: 'microhelp-hnm.firebasestorage.app',
  );

}