// File generated by `flutterfire configure`.
// Replace this file after running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured for this project. '
      'Run "flutterfire configure" to generate firebase_options.dart',
    );
  }
}
